set nocompatible
set encoding=utf8

" Automatically re-read a file that's been changed by another program
set autoread

"In normal and visual mode, map space bar to the colon
" noremap <Space> :
" vnomap <Space>:

set ruler
set cmdheight=2
set laststatus=2
"set showcmd




set backspace=eol,start,indent
set whichwrap+=<,>,h,l,b,[,]
"inoremap <Down> <C-o>gj
"inoremap <Up> <C-o>gk


"Searching
set ignorecase
set incsearch
set smartcase
set hlsearch
nnoremap <esc> :noh<CR>
set magic





set showmatch


set mouse=a

set noerrorbells
set visualbell


syntax enable
filetype on
filetype plugin on

set smarttab
set shiftwidth=3
set tabstop=3
set softtabstop=3
set autoindent
set smartindent

let NERDMenuMode="2"

autocmd VimEnter * nested :call tagbar#autoopen(1)
autocmd FileType * nested :call tagbar#autoopen(0)
autocmd BufEnter * nested :call tagbar#autoopen(0)

colorscheme desert
set background=dark
autocmd BufEnter * colorscheme desert
autocmd BufEnter *.php colorscheme twilight
autocmd BufEnter *.py colorscheme Tomorrow-Night

if has("gui_running")
	set guifont=Andale\ Mono\ 12
endif

